string      datalog_file_name                       # File name that need to be uploaded to IPFS
string[]    encrypt_recipient_addresses     ['']    # Addresses for file encryption, if empty, encryption will not be performed
---
string      datalog_hash                            # Hash of the datalog transaction